### ISSUE TITLE
running renga-ui image built with Makefile fails 

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renga-ui#23] opened 2017-09-18 14:07 UTC
the Makefile target for `renga-ui` should run the `npm` commands before building the docker image

**Comment by leafty** [comment] 2017-09-19 08:43
Duplicate of https://github.com/SwissDataScienceCenter/renga/issues/82.

**Comment by leafty** [comment] 2017-09-19 08:43
Closed as resolution will not happen here.

**Closed by leafty** 2017-09-19 08:43 UTC
Labels: bug
